export const AccountList = [
    {
      _id: "1",
      acc_uname: "john_doe",
      acc_eml: "john.doe@example.com",
      acc_pass: "password123",
      acc_pass_bckup: "backup123",
      acc_phn: "1234567890",
      acc_fname: "John Doe",
      acc_secphn: "0987654321",
      acc_typ: "Admin",
      acc_cat: "Category1",
      acc_comp: "Company1",
      acc_emp_code: "EMP001",
      acc_dept: "IT",
      acc_desig: "Manager",
      acc_lvl: "Level1",
      acc_reporting: "Jane Smith",
      acc_org: ["Org1"],
      acc_div: ["Div1"],
      acc_state: "State1",
      acc_base_loc_dist: "District1",
      acc_addrss: "123 Main St",
      acc_pan: "ABCDE1234F",
      acc_gst: "GST123456",
      acc_img: "image1.jpg",
      acc_img_publicid: "publicid1",
      acc_dob: "1990-01-01",
      acc_anniversary: "2015-01-01",
      status: "Active",
      createdOn: new Date(),
      updatedOn: new Date(),
    },
    {
      _id: "2",
      acc_uname: "jane_smith",
      acc_eml: "jane.smith@example.com",
      acc_pass: "password456",
      acc_pass_bckup: "backup456",
      acc_phn: "2345678901",
      acc_fname: "Jane Smith",
      acc_secphn: "1234567890",
      acc_typ: "User",
      acc_cat: "Category2",
      acc_comp: "Company2",
      acc_emp_code: "EMP002",
      acc_dept: "HR",
      acc_desig: "Executive",
      acc_lvl: "Level2",
      acc_reporting: "John Doe",
      acc_org: ["Org2"],
      acc_div: ["Div2"],
      acc_state: "State2",
      acc_base_loc_dist: "District2",
      acc_addrss: "456 Elm St",
      acc_pan: "FGHIJ5678K",
      acc_gst: "GST789012",
      acc_img: "image2.jpg",
      acc_img_publicid: "publicid2",
      acc_dob: "1992-02-02",
      acc_anniversary: "2018-02-02",
      status: "Active",
      createdOn: new Date(),
      updatedOn: new Date(),
    },
    {
      _id: "3",
      acc_uname: "michael_brown",
      acc_eml: "michael.brown@example.com",
      acc_pass: "password789",
      acc_pass_bckup: "backup789",
      acc_phn: "3456789012",
      acc_fname: "Michael Brown",
      acc_secphn: "2345678901",
      acc_typ: "Admin",
      acc_cat: "Category3",
      acc_comp: "Company3",
      acc_emp_code: "EMP003",
      acc_dept: "Finance",
      acc_desig: "Analyst",
      acc_lvl: "Level3",
      acc_reporting: "Jane Smith",
      acc_org: ["Org3"],
      acc_div: ["Div3"],
      acc_state: "State3",
      acc_base_loc_dist: "District3",
      acc_addrss: "789 Pine St",
      acc_pan: "KLMNO9012P",
      acc_gst: "GST345678",
      acc_img: "image3.jpg",
      acc_img_publicid: "publicid3",
      acc_dob: "1988-03-03",
      acc_anniversary: "2010-03-03",
      status: "Active",
      createdOn: new Date(),
      updatedOn: new Date(),
    },
    {
        _id: "4",
        acc_uname: "emma_watson",
        acc_eml: "emma.watson@example.com",
        acc_pass: "password101",
        acc_pass_bckup: "backup101",
        acc_phn: "4567890123",
        acc_fname: "Emma Watson",
        acc_secphn: "3456789012",
        acc_typ: "User",
        acc_cat: "Category4",
        acc_comp: "Company4",
        acc_emp_code: "EMP004",
        acc_dept: "Marketing",
        acc_desig: "Specialist",
        acc_lvl: "Level4",
        acc_reporting: "Michael Brown",
        acc_org: ["Org4"],
        acc_div: ["Div4"],
        acc_state: "State4",
        acc_base_loc_dist: "District4",
        acc_addrss: "101 Maple St",
        acc_pan: "PQRST1234U",
        acc_gst: "GST901234",
        acc_img: "image4.jpg",
        acc_img_publicid: "publicid4",
        acc_dob: "1995-04-04",
        acc_anniversary: "2020-04-04",
        status: "Active",
        createdOn: new Date(),
        updatedOn: new Date(),
    },
    {
        _id: "5",
        acc_uname: "oliver_jones",
        acc_eml: "oliver.jones@example.com",
        acc_pass: "password202",
        acc_pass_bckup: "backup202",
        acc_phn: "5678901234",
        acc_fname: "Oliver Jones",
        acc_secphn: "4567890123",
        acc_typ: "Admin",
        acc_cat: "Category5",
        acc_comp: "Company5",
        acc_emp_code: "EMP005",
        acc_dept: "Operations",
        acc_desig: "Supervisor",
        acc_lvl: "Level5",
        acc_reporting: "Emma Watson",
        acc_org: ["Org5"],
        acc_div: ["Div5"],
        acc_state: "State5",
        acc_base_loc_dist: "District5",
        acc_addrss: "202 Oak St",
        acc_pan: "UVWXY5678Z",
        acc_gst: "GST567890",
        acc_img: "image5.jpg",
        acc_img_publicid: "publicid5",
        acc_dob: "1985-05-05",
        acc_anniversary: "2012-05-05",
        status: "Active",
        createdOn: new Date(),
        updatedOn: new Date(),
    },
    {
        _id: "6",
        acc_uname: "sophia_taylor",
        acc_eml: "sophia.taylor@example.com",
        acc_pass: "password303",
        acc_pass_bckup: "backup303",
        acc_phn: "6789012345",
        acc_fname: "Sophia Taylor",
        acc_secphn: "5678901234",
        acc_typ: "User",
        acc_cat: "Category6",
        acc_comp: "Company6",
        acc_emp_code: "EMP006",
        acc_dept: "Sales",
        acc_desig: "Consultant",
        acc_lvl: "Level6",
        acc_reporting: "Oliver Jones",
        acc_org: ["Org6"],
        acc_div: ["Div6"],
        acc_state: "State6",
        acc_base_loc_dist: "District6",
        acc_addrss: "303 Birch St",
        acc_pan: "ABCDE6789F",
        acc_gst: "GST234567",
        acc_img: "image6.jpg",
        acc_img_publicid: "publicid6",
        acc_dob: "1993-06-06",
        acc_anniversary: "2017-06-06",
        status: "Active",
        createdOn: new Date(),
        updatedOn: new Date(),
    },
    {
        _id: "7",
        acc_uname: "liam_wilson",
        acc_eml: "liam.wilson@example.com",
        acc_pass: "password404",
        acc_pass_bckup: "backup404",
        acc_phn: "7890123456",
        acc_fname: "Liam Wilson",
        acc_secphn: "6789012345",
        acc_typ: "Admin",
        acc_cat: "Category7",
        acc_comp: "Company7",
        acc_emp_code: "EMP007",
        acc_dept: "Engineering",
        acc_desig: "Technician",
        acc_lvl: "Level7",
        acc_reporting: "Sophia Taylor",
        acc_org: ["Org7"],
        acc_div: ["Div7"],
        acc_state: "State7",
        acc_base_loc_dist: "District7",
        acc_addrss: "404 Cedar St",
        acc_pan: "FGHIJ9012K",
        acc_gst: "GST345678",
        acc_img: "image7.jpg",
        acc_img_publicid: "publicid7",
        acc_dob: "1991-07-07",
        acc_anniversary: "2016-07-07",
        status: "Active",
        createdOn: new Date(),
        updatedOn: new Date(),
    },
    {
        _id: "8",
        acc_uname: "ava_martin",
        acc_eml: "ava.martin@example.com",
        acc_pass: "password505",
        acc_pass_bckup: "backup505",
        acc_phn: "8901234567",
        acc_fname: "Ava Martin",
        acc_secphn: "7890123456",
        acc_typ: "User",
        acc_cat: "Category8",
        acc_comp: "Company8",
        acc_emp_code: "EMP008",
        acc_dept: "Support",
        acc_desig: "Coordinator",
        acc_lvl: "Level8",
        acc_reporting: "Liam Wilson",
        acc_org: ["Org8"],
        acc_div: ["Div8"],
        acc_state: "State8",
        acc_base_loc_dist: "District8",
        acc_addrss: "505 Walnut St",
        acc_pan: "KLMNO3456P",
        acc_gst: "GST678901",
        acc_img: "image8.jpg",
        acc_img_publicid: "publicid8",
        acc_dob: "1994-08-08",
        acc_anniversary: "2019-08-08",
        status: "Active",
        createdOn: new Date(),
        updatedOn: new Date(),
    },
    {
        _id: "9",
        acc_uname: "noah_clark",
        acc_eml: "noah.clark@example.com",
        acc_pass: "password606",
        acc_pass_bckup: "backup606",
        acc_phn: "9012345678",
        acc_fname: "Noah Clark",
        acc_secphn: "8901234567",
        acc_typ: "Admin",
        acc_cat: "Category9",
        acc_comp: "Company9",
        acc_emp_code: "EMP009",
        acc_dept: "Legal",
        acc_desig: "Advisor",
        acc_lvl: "Level9",
        acc_reporting: "Ava Martin",
        acc_org: ["Org9"],
        acc_div: ["Div9"],
        acc_state: "State9",
        acc_base_loc_dist: "District9",
        acc_addrss: "606 Chestnut St",
        acc_pan: "PQRST7890U",
        acc_gst: "GST890123",
        acc_img: "image9.jpg",
        acc_img_publicid: "publicid9",
        acc_dob: "1989-09-09",
        acc_anniversary: "2014-09-09",
        status: "Active",
        createdOn: new Date(),
        updatedOn: new Date(),
    },
    {
        _id: "10",
        acc_uname: "mia_davis",
        acc_eml: "mia.davis@example.com",
        acc_pass: "password707",
        acc_pass_bckup: "backup707",
        acc_phn: "0123456789",
        acc_fname: "Mia Davis",
        acc_secphn: "9012345678",
        acc_typ: "User",
        acc_cat: "Category10",
        acc_comp: "Company10",
        acc_emp_code: "EMP010",
        acc_dept: "Research",
        acc_desig: "Scientist",
        acc_lvl: "Level10",
        acc_reporting: "Noah Clark",
        acc_org: ["Org10"],
        acc_div: ["Div10"],
        acc_state: "State10",
        acc_base_loc_dist: "District10",
        acc_addrss: "707 Spruce St",
        acc_pan: "UVWXY1234Z",
        acc_gst: "GST012345",
        acc_img: "image10.jpg",
        acc_img_publicid: "publicid10",
        acc_dob: "1996-10-10",
        acc_anniversary: "2021-10-10",
        status: "Active",
        createdOn: new Date(),
        updatedOn: new Date(),
    }
];